name: check env

on:
  workflow_dispatch:
    inputs:
      word:
        type: string
        description: "The word"
        required: false

permissions:
  actions: read

env:
  JANKY_ENV_THING: ${{ inputs.word }}

jobs:
  the_job:
    # runs-on: ubuntu-latest
    # steps:
    #   - name: run it
    #     run: |
    #       env
    uses: toomanybees/the_action/.github/workflows/the-workflow.yml@main
