name: check env

on:
  workflow_dispatch:
    inputs:
      word:
        type: string
        description: "The word"
        required: false

permissions:
  actions: read

jobs:
  the_job:
    runs-on: ubuntu-latest
    steps:
      - name: run it
        run: |
          echo $(env)
          env
